# Generated by Django 3.1.2 on 2022-02-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=225)),
                ('description', models.TextField()),
                ('end_date', models.DateTimeField()),
                ('start_date', models.DateTimeField()),
                ('student_id_number', models.CharField(max_length=13)),
                ('teacher_id_number', models.CharField(max_length=13)),
                ('doc', models.FileField(null=True, upload_to='Assessments')),
                ('sub_assessment', models.FileField(null=True, upload_to='AssessmentsSub')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateTimeField()),
                ('subject_code', models.CharField(max_length=13)),
                ('student_id_number', models.CharField(max_length=13)),
                ('code', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance_code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateTimeField()),
                ('code', models.CharField(max_length=5)),
                ('teacher_id_number', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='BR_Subjects_Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=13)),
                ('id_number', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Classrooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id_number', models.CharField(max_length=13)),
                ('name', models.CharField(max_length=225)),
                ('student_id_number', models.CharField(max_length=13)),
                ('grade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=225)),
                ('description', models.TextField()),
                ('Startdate', models.DateTimeField()),
                ('Enddate', models.DateTimeField()),
                ('Author', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.IntegerField()),
                ('Second', models.IntegerField()),
                ('third', models.IntegerField()),
                ('fourth', models.IntegerField()),
                ('totalmarks', models.IntegerField()),
                ('id_number', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=225)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('Author', models.CharField(max_length=225)),
                ('image', models.ImageField(null=True, upload_to='studentNews')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=225)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('Author', models.CharField(max_length=225)),
                ('id_number', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('surname', models.CharField(max_length=225)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('id_number', models.CharField(max_length=13)),
                ('image', models.ImageField(null=True, upload_to='student')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id_number', models.CharField(max_length=13)),
                ('name', models.CharField(max_length=225)),
                ('subject_code', models.CharField(max_length=13)),
                ('grade', models.IntegerField()),
            ],
        ),
    ]
